/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


//import enumerations.EstadoPorta;
//import enumerations.EstadoWC;
import java.util.concurrent.Semaphore;

/**
 *
 * @author lopes
 */
public class Moedeiro extends javax.swing.JFrame implements Runnable{

    SharedInfo sharedObj;
    Semaphore semMoedeiroMain,semMainMoedeiro;
    Logs logSystem;
    
    public Moedeiro(SharedInfo sharedObj,Semaphore semMoedeiroMain,Semaphore semMainMoedeiro,Logs logSystem) {
        initComponents();
        this.sharedObj=sharedObj;
        this.logSystem=logSystem;
        this.semMoedeiroMain=semMoedeiroMain;
        this.semMainMoedeiro=semMainMoedeiro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbuttonMoeda5 = new javax.swing.JButton();
        jbuttonMoeda10 = new javax.swing.JButton();
        jbuttonMoeda20 = new javax.swing.JButton();
        jbuttonMoeda50 = new javax.swing.JButton();
        jbuttonMoeda100 = new javax.swing.JButton();
        jbuttonMoeda200 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Moedeiro");

        jbuttonMoeda5.setText("0.05");
        jbuttonMoeda5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonMoeda5MouseClicked(evt);
            }
        });

        jbuttonMoeda10.setText("0.10");
        jbuttonMoeda10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonMoeda10MouseClicked(evt);
            }
        });

        jbuttonMoeda20.setText("0.20");
        jbuttonMoeda20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonMoeda20MouseClicked(evt);
            }
        });

        jbuttonMoeda50.setText("0.50");
        jbuttonMoeda50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonMoeda50MouseClicked(evt);
            }
        });

        jbuttonMoeda100.setText("1.00");
        jbuttonMoeda100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonMoeda100MouseClicked(evt);
            }
        });

        jbuttonMoeda200.setText("2.00");
        jbuttonMoeda200.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonMoeda200MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbuttonMoeda50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbuttonMoeda100))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbuttonMoeda5)
                                .addGap(29, 29, 29)
                                .addComponent(jbuttonMoeda10)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbuttonMoeda20)
                            .addComponent(jbuttonMoeda200))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonMoeda5)
                    .addComponent(jbuttonMoeda10)
                    .addComponent(jbuttonMoeda20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonMoeda50)
                    .addComponent(jbuttonMoeda100)
                    .addComponent(jbuttonMoeda200))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonMoeda5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonMoeda5MouseClicked
        if (this.sharedObj.getPorta() == EstadoPorta.FECHADA && this.sharedObj.getEstado() == EstadoWC.LIVRE) {
            this.sharedObj.setDinheiroInserido(Math.round((sharedObj.getDinheiroInserido() + 0.05f) * 100.0) / 100.0);
        }
    }//GEN-LAST:event_jbuttonMoeda5MouseClicked

    private void jbuttonMoeda10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonMoeda10MouseClicked
        if (this.sharedObj.getPorta() == EstadoPorta.FECHADA && this.sharedObj.getEstado() == EstadoWC.LIVRE) {
            this.sharedObj.setDinheiroInserido(Math.round((sharedObj.getDinheiroInserido() + 0.10f) * 100.0) / 100.0);
        }
    }//GEN-LAST:event_jbuttonMoeda10MouseClicked

    private void jbuttonMoeda20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonMoeda20MouseClicked
        if (this.sharedObj.getPorta() == EstadoPorta.FECHADA && this.sharedObj.getEstado() == EstadoWC.LIVRE) {
            this.sharedObj.setDinheiroInserido(Math.round((sharedObj.getDinheiroInserido() + 0.20f) * 100.0) / 100.0);
        }
    }//GEN-LAST:event_jbuttonMoeda20MouseClicked

    private void jbuttonMoeda50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonMoeda50MouseClicked
        if (this.sharedObj.getPorta() == EstadoPorta.FECHADA && this.sharedObj.getEstado() == EstadoWC.LIVRE) {
            this.sharedObj.setDinheiroInserido(Math.round((sharedObj.getDinheiroInserido() + 0.50f) * 100.0) / 100.0);
        }
    }//GEN-LAST:event_jbuttonMoeda50MouseClicked

    private void jbuttonMoeda100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonMoeda100MouseClicked
        if (this.sharedObj.getPorta() == EstadoPorta.FECHADA && this.sharedObj.getEstado() == EstadoWC.LIVRE) {
            this.sharedObj.setDinheiroInserido(Math.round((sharedObj.getDinheiroInserido() + 1.00f) * 100.0) / 100.0);
        }
    }//GEN-LAST:event_jbuttonMoeda100MouseClicked

    private void jbuttonMoeda200MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonMoeda200MouseClicked
        if (this.sharedObj.getPorta() == EstadoPorta.FECHADA && this.sharedObj.getEstado() == EstadoWC.LIVRE) {
            this.sharedObj.setDinheiroInserido(Math.round((sharedObj.getDinheiroInserido() + 2.00f) * 100.0) / 100.0);
        }
    }//GEN-LAST:event_jbuttonMoeda200MouseClicked

    @Override
    public void run() {
        this.setVisible(true);
        this.setSize(400, 350);
        this.setLocation(400, 400);
        while (true) {
            try {
                this.semMainMoedeiro.acquire();
                if (this.sharedObj.getTroco()) {
                    this.sharedObj.setTroco(false);
                    double troco = (this.sharedObj.getDinheiroInserido() - this.sharedObj.preco);
                    if (troco > 0) {
                        this.sharedObj.setDinheiroInserido(this.sharedObj.getDinheiroInserido() - troco);
                        String msg = "Troco: " + String.format("%.2f", troco);
                        this.sharedObj.setAvisos(msg);
                        synchronized (logSystem) {
                            this.logSystem.registaAcao("Thread:Porta", "Troco devolvido:" + troco + "€");
                        }
                    }
                    this.semMoedeiroMain.release();
                } else {
                    this.sharedObj.setAvisos("Operacao cancelada. Dinheiro devolvido: " + this.sharedObj.getPreco() + "€");
                    this.semMoedeiroMain.release();
                }

            } catch (InterruptedException ex) {
            }
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbuttonMoeda10;
    private javax.swing.JButton jbuttonMoeda100;
    private javax.swing.JButton jbuttonMoeda20;
    private javax.swing.JButton jbuttonMoeda200;
    private javax.swing.JButton jbuttonMoeda5;
    private javax.swing.JButton jbuttonMoeda50;
    // End of variables declaration//GEN-END:variables
}
