/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.concurrent.Semaphore;

/**
 *
 * @author lopes
 */
public class Teclado extends javax.swing.JFrame implements Runnable{

    SharedInfo sharedObj;
    Semaphore semMainTeclado,semTeclado;
    
    public Teclado(SharedInfo sharedObj,Semaphore semMainTeclado) {
        initComponents();
        this.sharedObj=sharedObj;
        this.semMainTeclado=semMainTeclado;
        this.semTeclado=new Semaphore(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbuttonAbrir = new javax.swing.JButton();
        jbuttonFechar = new javax.swing.JButton();
        jbuttonCancelar = new javax.swing.JButton();
        jbuttonAberta = new javax.swing.JButton();
        jbuttonNeutro = new javax.swing.JButton();
        jbuttonFechada = new javax.swing.JButton();
        jbuttonReset = new javax.swing.JButton();
        jbuttonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Teclado");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Comandos:");

        jLabel3.setText("A - Abrir a Porta");

        jLabel4.setText("F - Fechar a Porta");

        jLabel5.setText("C - Cancelar a Operacao");

        jLabel6.setText("CA/CN/CF - Chave em Posicao Aberta/Neutra/Fechada");

        jLabel7.setText("R - Reset do Sistema");

        jLabel8.setText("L - Limpeza Forcada da Casa de Banho");

        jbuttonAbrir.setText("A");
        jbuttonAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonAbrirMouseClicked(evt);
            }
        });

        jbuttonFechar.setText("F");
        jbuttonFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonFecharMouseClicked(evt);
            }
        });
        jbuttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonFecharActionPerformed(evt);
            }
        });

        jbuttonCancelar.setText("C");
        jbuttonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonCancelarMouseClicked(evt);
            }
        });

        jbuttonAberta.setText("CA");
        jbuttonAberta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonAbertaMouseClicked(evt);
            }
        });

        jbuttonNeutro.setText("CN");
        jbuttonNeutro.setToolTipText("");
        jbuttonNeutro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonNeutroMouseClicked(evt);
            }
        });

        jbuttonFechada.setText("CF");
        jbuttonFechada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonFechadaMouseClicked(evt);
            }
        });

        jbuttonReset.setText("R");
        jbuttonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonResetMouseClicked(evt);
            }
        });

        jbuttonLimpar.setText("L");
        jbuttonLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonLimparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbuttonReset)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbuttonAberta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonNeutro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonFechada))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbuttonCancelar)
                        .addComponent(jbuttonFechar)
                        .addComponent(jbuttonAbrir))
                    .addComponent(jbuttonLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbuttonLimpar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbuttonAbrir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbuttonFechar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbuttonCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jbuttonAberta)
                            .addComponent(jbuttonNeutro)
                            .addComponent(jbuttonFechada))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jbuttonReset))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonFecharActionPerformed

    private void jbuttonAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonAbrirMouseClicked
        sharedObj.setBotao("A");
        semTeclado.release();
    }//GEN-LAST:event_jbuttonAbrirMouseClicked

    private void jbuttonFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonFecharMouseClicked
        sharedObj.setBotao("F");
        semTeclado.release();
    }//GEN-LAST:event_jbuttonFecharMouseClicked

    private void jbuttonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonCancelarMouseClicked
        sharedObj.setBotao("C");
        semTeclado.release();
    }//GEN-LAST:event_jbuttonCancelarMouseClicked

    private void jbuttonAbertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonAbertaMouseClicked
        sharedObj.setBotao("CA");
        semTeclado.release();
    }//GEN-LAST:event_jbuttonAbertaMouseClicked

    private void jbuttonNeutroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonNeutroMouseClicked
        sharedObj.setBotao("CN");
        semTeclado.release();
    }//GEN-LAST:event_jbuttonNeutroMouseClicked

    private void jbuttonFechadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonFechadaMouseClicked
        sharedObj.setBotao("CF");
        semTeclado.release();
    }//GEN-LAST:event_jbuttonFechadaMouseClicked

    private void jbuttonResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonResetMouseClicked
        sharedObj.setBotao("R");
        semTeclado.release();
    }//GEN-LAST:event_jbuttonResetMouseClicked

    private void jbuttonLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonLimparMouseClicked
       sharedObj.setBotao("L");
       semTeclado.release();
      
    }//GEN-LAST:event_jbuttonLimparMouseClicked

    @Override
    public void run() {
        this.setVisible(true);
        this.setSize(510, 350);
        this.setLocation(800, 400);
        
        while(true){
            try {
                semTeclado.acquire();
            } catch (InterruptedException ex) {}
            
            semMainTeclado.release();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbuttonAberta;
    private javax.swing.JButton jbuttonAbrir;
    private javax.swing.JButton jbuttonCancelar;
    private javax.swing.JButton jbuttonFechada;
    private javax.swing.JButton jbuttonFechar;
    private javax.swing.JButton jbuttonLimpar;
    private javax.swing.JButton jbuttonNeutro;
    private javax.swing.JButton jbuttonReset;
    // End of variables declaration//GEN-END:variables
}
